### ISSUE TITLE
Error in forest fire sampling

### ISSUE THREAD

**Issue by apurvamulay** [benedekrozemberczki/littleballoffur#6]
Hi,

While running the forest fire sampling code, I got an error that it is trying to pop an element from an empty deque.

  File "/opt/anaconda3/lib/python3.7/site-packages/littleballoffur/exploration_sampling/forestfiresampler.py", line 47, in _start_a_fire
    top_node = node_queue.popleft()
IndexError: pop from an empty deque

I am not sure if it was due to data or needs an empty/try-catch check or should it be handled by application code.  Hence opened an issue.

Thank you

**Comment by bricaud** [comment]
Hi,
This happens because the "fire" dies out before the number of required nodes (`number_of_nodes` input argument) is reached. It can happen when the fire does not find enough nodes to propagate to. This is the normal behavior of the algorithm, it was not supposed to collect a fixed amount of nodes in the original paper. You have to rerun it from another initial position or try decreasing the number of nodes required or increasing the burning probability. You can also catch the exception, depending if you want the original behavior or a fixed number of nodes.

**Comment by apurvamulay** [comment]
I see. Makes sense now. Thank you!
